Name:           ros-jade-visp-auto-tracker
Version:        0.10.0
Release:        0%{?dist}
Summary:        ROS visp_auto_tracker package

Group:          Development/Libraries
License:        GPLv2
URL:            http://wiki.ros.org/visp_auto_tracker
Source0:        %{name}-%{version}.tar.gz

Requires:       libdmtx-devel
Requires:       ros-jade-geometry-msgs
Requires:       ros-jade-message-filters
Requires:       ros-jade-resource-retriever
Requires:       ros-jade-roscpp
Requires:       ros-jade-sensor-msgs
Requires:       ros-jade-std-msgs
Requires:       ros-jade-visp
Requires:       ros-jade-visp-bridge
Requires:       ros-jade-visp-tracker
Requires:       zbar-devel
BuildRequires:  libdmtx-devel
BuildRequires:  ros-jade-catkin
BuildRequires:  ros-jade-geometry-msgs
BuildRequires:  ros-jade-message-filters
BuildRequires:  ros-jade-resource-retriever
BuildRequires:  ros-jade-roscpp
BuildRequires:  ros-jade-sensor-msgs
BuildRequires:  ros-jade-std-msgs
BuildRequires:  ros-jade-visp
BuildRequires:  ros-jade-visp-bridge
BuildRequires:  ros-jade-visp-tracker
BuildRequires:  zbar-devel

%description
Online automated pattern-based object tracker relying on visual servoing.
visp_auto_tracker wraps model-based trackers provided by ViSP visual servoing
library into a ROS package. The tracked object should have a QRcode of Flash
code pattern. Based on the pattern, the object is automaticaly detected. The
detection allows then to initialise the model-based trackers. When lost of
tracking achieves a new detection is performed that will be used to re-
initialize the tracker. This computer vision algorithm computes the pose (i.e.
position and orientation) of an object in an image. It is fast enough to allow
object online tracking using a camera.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/jade" \
        -DCMAKE_PREFIX_PATH="/opt/ros/jade" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/jade/setup.sh" ]; then . "/opt/ros/jade/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/jade

%changelog
* Mon Feb 13 2017 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.10.0-0
- Autogenerated by Bloom

* Mon Dec 21 2015 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.9.1-0
- Autogenerated by Bloom

* Sun Dec 20 2015 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.9.0-0
- Autogenerated by Bloom

* Tue Apr 28 2015 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.8.0-0
- Autogenerated by Bloom

