Name:           ros-melodic-visp-auto-tracker
Version:        0.10.0
Release:        1%{?dist}
Summary:        ROS visp_auto_tracker package

Group:          Development/Libraries
License:        GPLv2
URL:            http://wiki.ros.org/visp_auto_tracker
Source0:        %{name}-%{version}.tar.gz

Requires:       libdmtx-devel
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-message-filters
Requires:       ros-melodic-resource-retriever
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-visp
Requires:       ros-melodic-visp-bridge
Requires:       ros-melodic-visp-tracker
Requires:       zbar-devel
BuildRequires:  libdmtx-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-message-filters
BuildRequires:  ros-melodic-resource-retriever
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-visp
BuildRequires:  ros-melodic-visp-bridge
BuildRequires:  ros-melodic-visp-tracker
BuildRequires:  zbar-devel

%description
Online automated pattern-based object tracker relying on visual servoing.
visp_auto_tracker wraps model-based trackers provided by ViSP visual servoing
library into a ROS package. The tracked object should have a QRcode of Flash
code pattern. Based on the pattern, the object is automaticaly detected. The
detection allows then to initialise the model-based trackers. When lost of
tracking achieves a new detection is performed that will be used to re-
initialize the tracker. This computer vision algorithm computes the pose (i.e.
position and orientation) of an object in an image. It is fast enough to allow
object online tracking using a camera.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Sun May 26 2019 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.10.0-1
- Autogenerated by Bloom

