Name:           ros-melodic-visp-camera-calibration
Version:        0.11.0
Release:        1%{?dist}
Summary:        ROS visp_camera_calibration package

Group:          Development/Libraries
License:        GPLv2
URL:            http://wiki.ros.org/visp_camera_calibration
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-camera-calibration-parsers
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-message-generation
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-sensor-msgs
Requires:       ros-melodic-std-msgs
Requires:       ros-melodic-visp
Requires:       ros-melodic-visp-bridge
BuildRequires:  ros-melodic-camera-calibration-parsers
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-sensor-msgs
BuildRequires:  ros-melodic-std-msgs
BuildRequires:  ros-melodic-visp
BuildRequires:  ros-melodic-visp-bridge

%description
visp_camera_calibration allows easy calibration of cameras using a customizable
pattern and ViSP library.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Mon May 27 2019 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.11.0-1
- Autogenerated by Bloom

* Sun May 26 2019 Fabien Spindler <Fabien.Spindler@inria.fr> - 0.10.0-1
- Autogenerated by Bloom

